// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ValueStringBuilderFeatures.Net80
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class AppendCompositeFormatIntoAValueStringBuilderFeature
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "AppendCompositeFormat.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, System.Threading.Thread.CurrentThread.ManagedThreadId.ToString());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ValueStringBuilderFeatures/Net80", "Append CompositeFormat into a ValueStringBuilder", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Append CompositeFormat into a ValueStringBuilder")))
            {
                await global::ValueStringBuilderFeatures.Net80.AppendCompositeFormatIntoAValueStringBuilderFeature.FeatureSetupAsync(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Append composite format")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Append CompositeFormat into a ValueStringBuilder")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Span", "34", "Number: {0}, string: {1}.", "42", "Hello, world!", "Number: 42, string: Hello, world!.", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Span", "26", "{0}, string: {1}.", "42", "Hello, world!", "42, string: Hello, world!.", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Span", "33", "Number: {0}, string: {1}", "42", "Hello, world!", "Number: 42, string: Hello, world!", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Span", "15", "{0}{1}", "42", "Hello, world!", "42Hello, world!", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Span", "15", "{1}{0}", "42", "Hello, world!", "Hello, world!42", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Capacity", "34", "Number: {0}, string: {1}.", "42", "Hello, world!", "Number: 42, string: Hello, world!.", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Capacity", "26", "{0}, string: {1}.", "42", "Hello, world!", "42, string: Hello, world!.", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Capacity", "33", "Number: {0}, string: {1}", "42", "Hello, world!", "Number: 42, string: Hello, world!", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Capacity", "15", "{0}{1}", "42", "Hello, world!", "42Hello, world!", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Capacity", "15", "{1}{0}", "42", "Hello, world!", "Hello, world!42", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Span", "34", "Number: {0}, string: {1}.", "42", "Hello, world!", "Number: 42, string: Hello, world!.", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Capacity", "34", "Number: {0}, string: {1}.", "42", "Hello, world!", "Number: 42, string: Hello, world!.", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Span", "35", "Number: {0}, string: {1}.", "-42", "Hello, world!", "Number: -42, string: Hello, world!.", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Capacity", "35", "Number: {0}, string: {1}.", "-42", "Hello, world!", "Number: -42, string: Hello, world!.", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Span", "35", "Number: {0}, string: {1}.", "-42", "Hello, world!", "Number: -42, string: Hello, world!.", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Capacity", "35", "Number: {0}, string: {1}.", "-42", "Hello, world!", "Number: -42, string: Hello, world!.", null)]
        public async System.Threading.Tasks.Task AppendCompositeFormat(string initializationType, string initialLength, string compositeFormat, string firstValue, string secondValue, string result, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("InitializationType", initializationType);
            argumentsOfScenario.Add("InitialLength", initialLength);
            argumentsOfScenario.Add("CompositeFormat", compositeFormat);
            argumentsOfScenario.Add("FirstValue", firstValue);
            argumentsOfScenario.Add("SecondValue", secondValue);
            argumentsOfScenario.Add("Result", result);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Append composite format", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
    await testRunner.GivenAsync(string.Format("a ValueStringBuilder initialized with \'{0}\' of length {1}", initializationType, initialLength), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
 await testRunner.AndAsync(string.Format("I append the format \'{0}\' to the ValueStringBuilder with arguments {1} and \'{2}\'", compositeFormat, firstValue, secondValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 6
 await testRunner.WhenAsync("I get the string from the ValueStringBuilder", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
 await testRunner.ThenAsync(string.Format("the ValueStringBuilder string should be \'{0}\'", result), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
